### ISSUE TITLE
Exception in `orchidServe` when `src/orchid/resources` does not exist

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#308]
The `FileWatcher` which rebuilds the Orchid site on changes is throwing an exception when the resources directory does not exist. 

Stacktrace: 

```
java.nio.file.NoSuchFileException: /.../src/orchid/resources
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.nio.file.Files.walkFileTree(Files.java:2662)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at com.eden.orchid.api.server.FileWatcher.registerAll(FileWatcher.java:59)
        at com.eden.orchid.api.server.FileWatcher.startWatching(FileWatcher.java:41)
        at com.eden.orchid.api.tasks.TaskServiceImpl.watch(TaskServiceImpl.java:154)
        at com.eden.orchid.api.tasks.TaskService.watch(TaskService.java:34)
        at com.eden.orchid.impl.tasks.ServeTask.run(ServeTask.kt:24)
        at com.eden.orchid.api.tasks.TaskServiceImpl.runTask(TaskServiceImpl.java:83)
        at com.eden.orchid.api.tasks.TaskServiceImpl.onPostStart(TaskServiceImpl.java:74)
        at java.util.HashMap$Values.forEach(HashMap.java:981)
        at com.eden.orchid.api.OrchidContextImpl.start(OrchidContextImpl.java:74)
        at com.eden.orchid.Orchid.start(Orchid.java:102)
        at com.eden.orchid.Orchid.start(Orchid.java:69)
        at com.eden.orchid.Orchid.main(Orchid.java:60)

```

**Comment by cjbrooks12** [comment]
This fix has been released in [0.17.5](https://github.com/JavaEden/Orchid/releases/tag/0.17.5)
