### ISSUE TITLE
Unable to run orchid starter 

### ISSUE THREAD

**Issue by cchunduri** [JavaEden/Orchid#382]
Hi, 

Recently I got to know about Orchid, I thought of giving it a try for my personal blog. As per the documentation site, I've cloned the Orchid Starter and did `./gradlew orchidServe` but then I'm getting below exception, could you please help me to solve this

`INFO] ExternalResource: Downloading external resource https://orchid.run/meta/all.index.json
java.net.ProtocolException: Too many follow-up requests: 21
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at com.eden.orchid.api.resources.resource.ExternalResource.getContentBody(ExternalResource.kt:45)
	at com.eden.orchid.api.resources.resource.ExternalResource.getContentStream(ExternalResource.kt:60)
	at com.eden.orchid.api.resources.resource.OrchidResource.loadContent(OrchidResource.kt:113)
	at com.eden.orchid.api.resources.resource.OrchidResource.getContent(OrchidResource.kt:100)
	at com.eden.orchid.api.resources.resource.ExternalResource.getContent(ExternalResource.kt:70)
	at com.eden.orchid.api.resources.resource.OrchidResource.parseContent(OrchidResource.kt:56)
	at com.eden.orchid.impl.generators.ExternalIndexGenerator.startIndexing(ExternalIndexGenerator.kt:46)
	at com.eden.orchid.impl.generators.ExternalIndexGenerator.startIndexing(ExternalIndexGenerator.kt:22)
	at com.eden.orchid.api.generators.GeneratorServiceImpl.indexGenerator(GeneratorServiceImpl.java:111)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2739)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.eden.orchid.api.generators.GeneratorServiceImpl.startIndexing(GeneratorServiceImpl.java:91)
	at com.eden.orchid.api.generators.GeneratorService.startIndexing(GeneratorService.java:12)
	at com.eden.orchid.api.tasks.TaskServiceImpl.build(TaskServiceImpl.java:130)
	at com.eden.orchid.api.tasks.TaskService.build(TaskService.java:26)
	at com.eden.orchid.impl.tasks.ServeTask.run(ServeTask.kt:16)
	at com.eden.orchid.api.tasks.TaskServiceImpl.runTask(TaskServiceImpl.java:79)
	at com.eden.orchid.api.tasks.TaskServiceImpl.onPostStart(TaskServiceImpl.java:70)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
	at com.eden.orchid.api.OrchidContextImpl.start(OrchidContextImpl.java:100)
	at com.eden.orchid.Orchid.start(Orchid.java:96)
	at com.eden.orchid.Orchid.start(Orchid.java:62)
	at com.eden.orchid.Orchid.internalMain(Orchid.java:54)
	at com.eden.orchid.Orchid.main(Orchid.java:45)
org.json.JSONException: JSONObject["ownKey"] not found.
	at org.json.JSONObject.get(JSONObject.java:566)
	at org.json.JSONObject.getString(JSONObject.java:851)
	at com.eden.orchid.api.indexing.OrchidIndex$Companion.fromJSON(OrchidIndex.kt:197)
	at com.eden.orchid.impl.generators.ExternalIndexGenerator.startIndexing(ExternalIndexGenerator.kt:47)
	at com.eden.orchid.impl.generators.ExternalIndexGenerator.startIndexing(ExternalIndexGenerator.kt:22)
	at com.eden.orchid.api.generators.GeneratorServiceImpl.indexGenerator(GeneratorServiceImpl.java:111)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2739)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.eden.orchid.api.generators.GeneratorServiceImpl.startIndexing(GeneratorServiceImpl.java:91)
	at com.eden.orchid.api.generators.GeneratorService.startIndexing(GeneratorService.java:12)
	at com.eden.orchid.api.tasks.TaskServiceImpl.build(TaskServiceImpl.java:130)
	at com.eden.orchid.api.tasks.TaskService.build(TaskService.java:26)
	at com.eden.orchid.impl.tasks.ServeTask.run(ServeTask.kt:16)
	at com.eden.orchid.api.tasks.TaskServiceImpl.runTask(TaskServiceImpl.java:79)
	at com.eden.orchid.api.tasks.TaskServiceImpl.onPostStart(TaskServiceImpl.java:70)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
	at com.eden.orchid.api.OrchidContextImpl.start(OrchidContextImpl.java:100)
	at com.eden.orchid.Orchid.start(Orchid.java:96)
	at com.eden.orchid.Orchid.start(Orchid.java:62)
	at com.eden.orchid.Orchid.internalMain(Orchid.java:54)
	at com.eden.orchid.Orchid.main(Orchid.java:45)
[ERROR] Errors:
[ERROR] Orchid: 
[ERROR]     - Something went wrong running `

Below are the details of my environment
**Machine:** Mac OS
**IDE:** Intellij
**Gradle:** 5.6.2
**Java:** 11

**Comment by cjbrooks12** [comment]
That URL exists, so it might be an issue with Netlify hosting that file. Removing [this block](https://github.com/orchidhq/OrchidStarter/blob/master/src/orchid/resources/config.yml#L63-L66) from `config.yml` should fix it

**Comment by cchunduri** [comment]
@cjbrooks12, thank you very much for the help, it worked for me after removing the block.
